SELECT T.ITEM_ID
     , I.ITEM_NAME
     , I.RARITY
  FROM ITEM_TREE T
 INNER JOIN ITEM_INFO I
    ON I.ITEM_ID = T.ITEM_ID
  LEFT JOIN ITEM_TREE TR
    ON TR.PARENT_ITEM_ID = T.ITEM_ID
 WHERE TR.PARENT_ITEM_ID IS NULL
 ORDER BY T.ITEM_ID DESC
;