SELECT U.USER_ID
     , U.NICKNAME
     , CONCAT(U.CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2)AS `전체주소`
     , CONCAT(SUBSTRING(U.TLNO, 1, 3), '-', SUBSTRING(U.TLNO, 4, 4), '-', SUBSTRING(U.TLNO, 8, 4)) AS `전화번호`
  FROM USED_GOODS_BOARD B
 INNER JOIN USED_GOODS_USER U
    ON U.USER_ID = B.WRITER_ID
 GROUP BY B.WRITER_ID
HAVING COUNT(*) > 2
 ORDER BY U.USER_ID DESC