SELECT I.ANIMAL_ID
     , I.ANIMAL_TYPE
     , I.NAME
  FROM ANIMAL_INS I
 INNER JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
 WHERE (I.SEX_UPON_INTAKE != 'Spayed Female' AND I.SEX_UPON_INTAKE != 'Neutered Male')
   AND (O.SEX_UPON_OUTCOME = 'Spayed Female' OR O.SEX_UPON_OUTCOME = 'Neutered Male')
 ORDER BY I.ANIMAL_ID
;