WITH T AS (
SELECT ID
     , ROW_NUMBER() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS RN
  FROM FISH_INFO
)

SELECT A.ID AS ID
     , B.FISH_NAME AS FISH_NAME
     , A.LENGTH AS LENGTH
  FROM FISH_INFO A
  JOIN FISH_NAME_INFO B
    ON A.FISH_TYPE = B.FISH_TYPE
  JOIN T
    ON A.ID = T.ID
   AND T.RN = 1
 ORDER BY A.ID
;