WITH SCORE_TABLE AS (
SELECT MAX(SUM_SCORE) AS `MAX_SCORE`
  FROM (
      SELECT SUM(SCORE) AS `SUM_SCORE`
        FROM HR_GRADE G
       WHERE YEAR = '2022'
       GROUP BY EMP_NO
  ) T
)

SELECT SUM(G.SCORE) AS `SCORE`
     , E.EMP_NO
     , E.EMP_NAME
     , E.POSITION
     , E.EMAIL
  FROM HR_EMPLOYEES E
 INNER JOIN HR_GRADE G
    ON G.EMP_NO = E.EMP_NO
 WHERE YEAR = '2022'
 GROUP BY E.EMP_NO
HAVING SUM(G.SCORE) = (SELECT `MAX_SCORE` FROM SCORE_TABLE)
;
