SELECT BRD.TITLE
     , BRD.BOARD_ID
     , REP.REPLY_ID
     , REP.WRITER_ID
     , REP.CONTENTS
     , DATE_FORMAT(REP.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
  FROM USED_GOODS_BOARD BRD
 INNER JOIN USED_GOODS_REPLY REP
    ON REP.BOARD_ID = BRD.BOARD_ID
 WHERE BRD.CREATED_DATE BETWEEN '20221001' AND '20221031'
 ORDER BY REP.CREATED_DATE ASC, BRD.TITLE ASC
;