WITH MAX_VIEW AS (
    SELECT BOARD_ID
      FROM USED_GOODS_BOARD
     ORDER BY VIEWS DESC
     LIMIT 1
)
SELECT CONCAT('/home/grep/src/', M.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS `FILE_PATH`
  FROM MAX_VIEW M
 INNER JOIN USED_GOODS_FILE F
    ON F.BOARD_ID = M.BOARD_ID
 ORDER BY FILE_ID DESC